USE [master]
GO

/****** Object:  Database [Activos]    Script Date: 12/10/2020 10:17:06 ******/
CREATE DATABASE [Activos]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Activos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Activos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Activos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Activos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Activos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Activos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Activos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Activos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Activos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Activos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Activos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Activos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Activos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Activos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Activos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Activos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Activos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Activos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Activos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Activos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Activos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Activos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Activos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Activos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Activos] SET  MULTI_USER 
GO

ALTER DATABASE [Activos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Activos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Activos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Activos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Activos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Activos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Activos] SET  READ_WRITE 
GO


USE [Activos]
GO

/****** Object:  Table [dbo].[Simbolos]    Script Date: 12/10/2020 10:17:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Simbolos](
	[Date] [date] NOT NULL,
	[Symbol] [nchar](10) NOT NULL,
	[Open] [float] NULL,
	[High] [float] NULL,
	[Low] [float] NULL,
	[Close] [float] NULL,
 CONSTRAINT [PK_Simbolos] PRIMARY KEY CLUSTERED 
(
	[Symbol] ASC,
	[Date] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
